export default {
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  ADD_MOVIE: 'ADD_MOVIE',
  START_FETCHING_MOVIE: 'START_FETCHING_MOVIE',
  CANCEL_FETCHING_MOVIE: 'CANCEL_FETCHING_MOVIE',
  ADD_MOVIES: 'ADD_MOVIES',
  START_FETCHING_MOVIES: 'START_FETCHING_MOVIES',
  CANCEL_FETCHING_MOVIES: 'CANCEL_FETCHING_MOVIES',
}